ocp:
  client: "oc"
  credentials:
    - id: acr-devops-${deploymentEnvironment}
      items:
        - key: username
          varkey: AZURE_REGISTRY_USERNAME
        - key: password
          varkey: AZURE_REGISTRY_PASSWORD
    - id: ocp_registry_credentials_${deploymentEnvironment}
      items:
        - key: username
          varkey: EXTERNAL_REGISTRY_USERNAME
        - key: password
          varkey: EXTERNAL_REGISTRY_PASSWORD
    - id: token-github-${deploymentEnvironment}
      items:
        - key: username
          varkey: GIT_USERNAME
        - key: password
          varkey: GIT_PASSWORD
aks:
  client: "kubectl"
  credentials:
      - id: acr-devops-${deploymentEnvironment}
        items:
          - key: username
            varkey: AZURE_REGISTRY_USERNAME
          - key: password
            varkey: AZURE_REGISTRY_PASSWORD
      - id: ${project}_az_sp_${deploymentEnvironment}
        items:
          - key: secret
            varkey: AKS_SP
      - id: ${project}_az_tenant_${deploymentEnvironment}
        items:
          - key: secret
            varkey: AZ_TENANT
      - id: ${project}_az_certificate_${deploymentEnvironment}
        items:
          - key: fileValue
            varkey: AKS_CERTIFICATE
            type: FileBinding
      - id: token-github-${deploymentEnvironment}
        items:
          - key: username
            varkey: GIT_USERNAME
          - key: password
            varkey: GIT_PASSWORD